In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [2]:
data_file="customers.xlsx"
customer_data=pd.read_excel(data_file)
sex=pd.get_dummies(customer_data['Sex'], drop_first=True)
savings_acc=pd.get_dummies(customer_data['Savings acc'], drop_first=True)

customer_data.drop(['Post code','Sex','Location','Current Account', 'Savings acc', 'ISA'], axis=1, inplace=True)
customer_data=pd.concat([customer_data, savings_acc], axis=1)
creditcard=[]

In [3]:
for i in range(len(customer_data)):
    if((customer_data.loc[i,'Credit card balance'])>0):
        creditcard.append(1)
    else:
        creditcard.append(0)
customer_data['has_Creditcard']=pd.Series(creditcard)
customer_data.head()

ID  Age  Average Balance  Monthly Income  Credit card balance  \
0   1   22               50             122                  300   
1   2   20              127             748                  762   
2   3   61             2490            7297                    0   
3   4   50             2852            7486                19964   
4   5   41             2942            7461                    0   

   Mortgage balance  Overdraft  Premium Saver  Savings Builder  has_Creditcard  
0                 0          0              0                1               1  
1                 0          0              0                1               1  
2                 0          1              0                0               0  
3                 0          0              0                0               1  
4            208908          0              0                0               0

In [4]:
customer_data.drop('Credit card balance',axis=1, inplace=True)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(customer_data.drop('has_Creditcard',axis=1), 
           customer_data['has_Creditcard'], test_size=0.20, 
            random_state=150)

In [6]:
logmodel = LogisticRegression(max_iter=10000,solver='saga', penalty='l1')
logmodel.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=10000, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='saga',
          tol=0.0001, verbose=0, warm_start=False)

In [7]:
train_pred=logmodel.predict(X_train)
Predictions = logmodel.predict(X_test)

In [8]:
from sklearn.metrics import classification_report
print(classification_report(y_test,Predictions))
print(classification_report(y_train, train_pred))

              precision    recall  f1-score   support

           0       0.52      0.49      0.50      1045
           1       0.47      0.50      0.49       956

   micro avg       0.49      0.49      0.49      2001
   macro avg       0.50      0.50      0.49      2001
weighted avg       0.50      0.49      0.49      2001

              precision    recall  f1-score   support

           0       0.51      0.50      0.51      3983
           1       0.52      0.53      0.52      4017

   micro avg       0.51      0.51      0.51      8000
   macro avg       0.51      0.51      0.51      8000
weighted avg       0.51      0.51      0.51      8000



In [9]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, Predictions))
print(confusion_matrix(y_train, train_pred))

[[511 534]
 [477 479]]
[[1985 1998]
 [1887 2130]]


In [10]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, Predictions))
print(accuracy_score(y_train, train_pred))

0.4947526236881559
0.514375


In [11]:
logmodel.predict_proba(X_test)

array([[0.49336587, 0.50663413],
       [0.51476236, 0.48523764],
       [0.51978579, 0.48021421],
       ...,
       [0.48336301, 0.51663699],
       [0.50954837, 0.49045163],
       [0.49509343, 0.50490657]])